### ISSUE TITLE
How can I read image file with epub-parser?

### ISSUE THREAD

**Issue by jpfong** [gaoxiaoliangz/epub-parser#11]
Hi,

some epub files contain images, I would like to extract them? I'm using nodeJS, and I don't know how to import util functions with "require".

Thanks!

**Comment by gaoxiaoliangz** [comment]
Sorry for the late response. It is actually in the docs. Your can use `Section.prototype.toHtmlObjects`(which will convert images to base64 strings) to achieve that.
