### ISSUE TITLE
"GeneralObject" and "HtmlNodeObject" unrecognized with TypeScript 

### ISSUE THREAD

**Issue by ShiratGlazer** [gaoxiaoliangz/epub-parser#18]
Hi, 
When I try to use the package with typescript, tsc says that "GeneralObject" and "HtmlNodeObject" unrecognized.
Changing those type to "any" works for me - but there is one problem: 
I want to deploy my work on Heroku, and I cannot do so because it downloads the package itself.
I fixed it by changing the package and adding it to my code (not under the node_modules folder)
Just wanted to ask you if you think there is a better solution :)
Thank you!

**Comment by gaoxiaoliangz** [comment]
Thanks for the feedback, I'll look into it when I have time.

**Comment by gaoxiaoliangz** [comment]
It has been fixed in v2.0.2
